[package]
name = "vblockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vblockchain"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.19"
crypto-hash = "0.3.4"